name = "Quantum_TLM_TUR"
authors = ["Janovitch"]
[compat]
julia = "1.11.6"
DrWatson = "2.19.1"
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuantumFCS = "f61df7d1-40df-4ff5-bdc9-ea200d60bc8f"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

